controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /api/token/authentication
    methods: ['POST']

refresh_jwt:
    path: /api/token/refresh
    methods: ['POST']

logout:
    path: /api/token/invalidate
    methods: ['POST']